# Generated by Django 6.0 on 2026-01-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('clock_in_location', models.CharField(blank=True, max_length=255)),
                ('clock_out_location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(default='absent', max_length=50)),
                ('worked_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'attendance',
                'ordering': ['-date', '-clock_in'],
            },
        ),
    ]
