# Generated by Django 6.0 on 2026-01-04 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('employees', '0005_alter_employee_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('justification', models.TextField()),
                ('status', models.CharField(default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employees', models.ManyToManyField(related_name='overtime_assignments', to='employees.employee')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_initiations', to='employees.employee')),
            ],
            options={
                'db_table': 'overtime_requests',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
