# Generated by Django 6.0 on 2026-01-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_workschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='hours_per_day',
            field=models.CharField(default='08:00', max_length=10),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='hours_per_week',
            field=models.CharField(default='40:00', max_length=10),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='schedule_type',
            field=models.CharField(default='Fixed Time', max_length=50),
        ),
    ]
