# Generated by Django 5.2.6 on 2026-01-18 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_workschedule_hours_per_day_and_more"),
        ("employees", "0011_remove_employee_bank_account_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeWorkScheduleLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_schedule_link",
                        to="employees.employee",
                    ),
                ),
                (
                    "work_schedule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_links",
                        to="attendance.workschedule",
                    ),
                ),
            ],
            options={
                "db_table": "employee_work_schedule_link",
            },
        ),
    ]
