export const now = (mins = 0) => new Date(Date.now() - mins * 60_000).toISOString();

export const MOCK_USERS = [
  { id: 1, name: "John Doe", email: "john.doe@example.com", dept: "Sales" },
  { id: 2, name: "Sarah Johnson", email: "sarah.johnson@example.com", dept: "Engineering" },
  { id: 3, name: "Daniel Mekonnen", email: "daniel.mekonnen@example.com", dept: "Warehouse" },
];

export const MOCK_NOTIFICATIONS = [
  {
    id: "n1",
    type: "SYSTEM",
    category: "system",
    title: "New integration announcement",
    message: "A new HR integration has been enabled for payroll exports.",
    createdAt: now(60),
    unread: true,
    senderRole: "SYSTEM",
    receivers: ["SYSTEM_ADMIN"],
    meta: { severity: "info" },
  },
  {
    id: "n2",
    type: "TRAINING",
    category: "hr",
    title: "Training session reminder",
    message: "Don't forget to join the upcoming training session on Friday.",
    createdAt: now(120),
    unread: true,
    senderRole: "HR_MANAGER",
    receivers: ["EMPLOYEE", "DEPARTMENT_MANAGER"],
    meta: { sessionId: "t-001" },
  },
  {
    id: "n3",
    type: "ATTENDANCE",
    category: "attendance",
    title: "Missing clock-out detected",
    message: "John Doe did not clock out yesterday — please review.",
    createdAt: now(240),
    unread: false,
    senderRole: "SYSTEM",
    receivers: ["DEPARTMENT_MANAGER", "HR_MANAGER"],
    meta: { employeeId: 1, date: "2025-11-23" },
  },
  {
    id: "n4",
    type: "LEAVE",
    category: "leave",
    title: "Leave request pending",
    message: "Leave request from Sarah Johnson requires your approval.",
    createdAt: now(20),
    unread: true,
    senderRole: "EMPLOYEE",
    receivers: ["DEPARTMENT_MANAGER"],
    meta: { requestId: "leave-123", employeeId: 2 },
  },
  {
    id: "n5",
    type: "LEAVE",
    category: "leave",
    title: "Leave request pending",
    message: "Leave request from Sarah Johnson requires your approval.",
    createdAt: now(20),
    unread: true,
    senderRole: "EMPLOYEE",
    receivers: ["DEPARTMENT_MANAGER"],
    meta: { requestId: "leave-123", employeeId: 2 },
  },
  {
    id: "n6",
    type: "LEAVE",
    category: "leave",
    title: "Leave request pending",
    message: "Leave request from Sarah Johnson requires your approval.",
    createdAt: now(20),
    unread: true,
    senderRole: "EMPLOYEE",
    receivers: ["DEPARTMENT_MANAGER"],
    meta: { requestId: "leave-123", employeeId: 2 },
  },
  {
    id: "n7",
    type: "LEAVE",
    category: "leave",
    title: "Leave request pending",
    message: "Leave request from Sarah Johnson requires your approval.",
    createdAt: now(20),
    unread: true,
    senderRole: "EMPLOYEE",
    receivers: ["DEPARTMENT_MANAGER"],
    meta: { requestId: "leave-123", employeeId: 2 },
  },
];
// Sample dummy notifications used for testing without backend.
