# Generated by Django 6.0 on 2026-01-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
