# Generated by Django 5.2.6 on 2026-01-18 12:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_companyinfo_country_code_companyinfo_description"),
        ("departments", "0004_remove_department_tax_code"),
        ("employees", "0010_remove_employee_tax_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyOrgNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("in_org_chart", models.BooleanField(default=False)),
                ("org_x", models.FloatField(default=0)),
                ("org_y", models.FloatField(default=0)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="org_node",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "company_org_nodes",
            },
        ),
        migrations.CreateModel(
            name="EmployeeContractInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "contract_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "contract_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("contract_start_date", models.DateField(blank=True, null=True)),
                ("contract_end_date", models.DateField(blank=True, null=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contract_info",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_contract_info",
            },
        ),
        migrations.CreateModel(
            name="EmployeeJobInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("position", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "employment_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "join_date",
                    models.DateField(
                        blank=True, default=datetime.date.today, null=True
                    ),
                ),
                ("service_years", models.IntegerField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_infos",
                        to="departments.department",
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_info",
                        to="employees.employee",
                    ),
                ),
                (
                    "line_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_job_infos",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_job_info",
            },
        ),
    ]
