# Generated by Django 6.0 on 2026-01-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_link_notification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('message', 'Message'), ('request', 'Request'), ('system', 'System'), ('leave', 'Leave'), ('promotion', 'Promotion'), ('policy', 'Policy')], default='info', max_length=50),
        ),
    ]
