# Generated by Django 6.0 on 2026-01-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('message', 'Message'), ('request', 'Request'), ('system', 'System'), ('leave', 'Leave'), ('promotion', 'Promotion'), ('policy', 'Policy'), ('hr', 'HR'), ('attendance', 'Attendance'), ('payroll', 'Payroll')], default='info', max_length=50),
        ),
    ]
