# Generated by Django 6.0 on 2026-01-09 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_initial'),
        ('payroll', '0004_taxcodeversion_exemptions_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_default', to='payroll.taxcode'),
        ),
    ]
