# Generated by Django 6.0 on 2026-01-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_department_tax_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='tax_code',
        ),
    ]
