# Generated by Django 6.0 on 2026-01-02 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_in_org_chart'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxcode',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='taxcodeversion',
            options={'ordering': ['-valid_from']},
        ),
        migrations.RenameField(
            model_name='taxcode',
            old_name='code_id',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='taxcode',
            old_name='is_enabled',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='taxcodeversion',
            old_name='compliance',
            new_name='compliance_notes',
        ),
        migrations.AlterUniqueTogether(
            name='taxcodeversion',
            unique_together={('tax_code', 'version')},
        ),
        migrations.AddField(
            model_name='taxcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxcode',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taxcodeversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxcodeversion',
            name='rounding_rules',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='taxcodeversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taxcodeversion',
            name='income_tax_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='taxcodeversion',
            name='pension_config',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='taxcodeversion',
            name='version',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Salary'), ('formula', 'Custom Formula')], default='fixed', max_length=20)),
                ('default_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('formula', models.TextField(blank=True)),
                ('is_taxable', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowances', to='payroll.taxcode')),
            ],
            options={
                'db_table': 'allowances',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('calculation_type', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Salary'), ('tiered', 'Tiered (Tax Brackets)'), ('formula', 'Custom Formula')], default='fixed', max_length=20)),
                ('default_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('formula', models.TextField(blank=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('is_pre_tax', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('applies_to', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deductions', to='payroll.taxcode')),
            ],
            options={
                'db_table': 'deductions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('applies_to', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tax_code_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_brackets', to='payroll.taxcodeversion')),
            ],
            options={
                'db_table': 'tax_brackets',
                'ordering': ['min_income'],
            },
        ),
        migrations.RemoveField(
            model_name='taxcodeversion',
            name='deductions',
        ),
        migrations.RemoveField(
            model_name='taxcodeversion',
            name='exemptions',
        ),
        migrations.RemoveField(
            model_name='taxcodeversion',
            name='rounding',
        ),
        migrations.CreateModel(
            name='EmployeeAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.allowance')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_allowances', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_allowances',
                'unique_together': {('employee', 'allowance')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.deduction')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_deductions', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_deductions',
                'unique_together': {('employee', 'deduction')},
            },
        ),
    ]
