# Generated by Django 6.0 on 2026-01-05 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_work_schedule'),
        ('payroll', '0002_alter_taxcode_options_alter_taxcodeversion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payslip',
            name='deductions',
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_approved', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payrollperiod',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_submitted', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='absent_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='gross_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='has_issues',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payslip',
            name='issue_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payslip',
            name='leave_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_pay',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='overtime_rate',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.taxcode'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tax_code_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.taxcodeversion'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payslip',
            name='worked_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_created', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='payrollperiod',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('pending_approval', 'Pending HR Approval'), ('approved', 'Approved'), ('finalized', 'Finalized'), ('rolled_back', 'Rolled Back')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='PayrollApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('generated', 'Generated'), ('submitted', 'Submitted for Approval'), ('approved', 'Approved'), ('finalized', 'Finalized'), ('rolled_back', 'Rolled Back')], max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('previous_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='payroll.payrollperiod')),
            ],
            options={
                'db_table': 'payroll_approval_logs',
                'ordering': ['-performed_at'],
            },
        ),
    ]
