# Generated by Django 6.0 on 2026-01-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_remove_payslip_deductions_payrollperiod_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxcodeversion',
            name='exemptions_config',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='taxcodeversion',
            name='statutory_deductions_config',
            field=models.JSONField(default=list),
        ),
    ]
