# Generated by Django 5.2.6 on 2026-01-18 12:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0010_remove_employee_tax_code"),
        ("payroll", "0004_taxcodeversion_exemptions_config_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeePayrollInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="Active", max_length=50)),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("last_working_date", models.DateField(blank=True, null=True)),
                (
                    "offset",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "one_off",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payroll_info",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_payroll_info",
            },
        ),
    ]
