# Generated by Django 5.2.6 on 2026-01-18 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0005_allowance_tax_code_version"),
        ("payroll", "0005_employeepayrollinfo"),
    ]

    operations = []
