# Generated by Django 6.0 on 2026-01-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('efficiency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='efficiencyevaluation',
            options={'ordering': ['-submitted_at']},
        ),
        migrations.RemoveField(
            model_name='efficiencyevaluation',
            name='data',
        ),
        migrations.AddField(
            model_name='efficiencyevaluation',
            name='report_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='efficiencyevaluation',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
    ]
