# Generated by Django 6.0 on 2026-01-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcementattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
