# Generated by Django 6.0 on 2026-01-02 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_taxcode_options_alter_taxcodeversion_options_and_more'),
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='Tax code used for salary calculations in this organization', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='payroll.taxcode'),
        ),
    ]
