# Generated by Django 5.2.6 on 2026-01-18 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0010_remove_employee_tax_code"),
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeAddressInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_address", models.TextField(blank=True, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="address_info",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_address_info",
            },
        ),
        migrations.CreateModel(
            name="EmployeeEmergencyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(blank=True, max_length=200, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "relationship",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("postcode", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_info",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_emergency_info",
            },
        ),
        migrations.CreateModel(
            name="EmployeeGeneralInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "personal_tax_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "social_insurance",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "health_care",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_info",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "db_table": "employee_general_info",
            },
        ),
    ]
