# Generated by Django 6.0 on 2026-01-02 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_bank_account_alter_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='org_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='employee',
            name='org_y',
            field=models.FloatField(default=0),
        ),
    ]
