# Generated by Django 6.0 on 2026-01-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employee_org_x_employee_org_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='in_org_chart',
            field=models.BooleanField(default=False),
        ),
    ]
