# Generated by Django 6.0 on 2026-01-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_in_org_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
