# Generated by Django 6.0 on 2026-01-04 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_workschedule'),
        ('employees', '0005_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='attendance.workschedule'),
        ),
    ]
