# Generated by Django 6.0 on 2026-01-07 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedocument',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='employeedocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='document_type',
            field=models.CharField(blank=True, default='General', max_length=50),
        ),
    ]
