# Generated by Django 6.0 on 2026-01-07 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeedocument_notes_employeedocument_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
