# Generated by Django 6.0.1 on 2026-01-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_remove_employee_tax_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
    ]
