export const mainHeaderSearch = {
  Manager: [
    { label: "Dashboard", path: "/hr_dashboard" },
    { label: "Employee Directory", path: "/hr_dashboard/Employee_Directory" },
    { label: "Upload Documents", path: "/hr_dashboard/org-chart" },
    { label: "Department Attendance", path: "/hr_dashboard/Department_Attendance" },
    { label: "My Attendance", path: "/hr_dashboard/myattendance" },
    { label: "Approve/Reject Requests", path: "/hr_dashboard/Approve_Reject" },
    { label: "Payroll Reports", path: "/hr_dashboard/Payroll_report" },
    { label: "My Payroll", path: "/hr_dashboard/MyPayroll" },
    { label: "Employee Efficiency Reports", path: "/hr_dashboard/efficiency_report" },
    { label: "Create Efficiency Form", path: "/hr_dashboard/efficiencyhr" },
    { label: "Policy", path: "/hr_dashboard/policies" },
    { label: "View Notifications", path: "/hr_dashboard/view_notification" },
    { label: "Send Notifications", path: "/hr_dashboard/send_notification" },
    { label: "Profile", path: "/hr_dashboard/profile" },
    { label: "Tax Codes", path: "/hr_dashboard/tax_code" },
    { label: "Announcements", path: "/hr_dashboard/Announcement" },
    { label: "Add Employee", path: "/hr_dashboard/Addemployee" },
    { label: "Promote Employee", path: "/hr_dashboard/PromoteEmployee" },
    { label: "Assign Department", path: "/hr_dashboard/AssignDepartment" },
    { label: "Organization Chart", path: "/hr_dashboard/org-chart" },
    { label: "Help Center", path: "/hr_dashboard/HelpCenter" },
    { label: "Settings", path: "/hr_dashboard/setting" },
    { label: "Clock In/Out", path: "/hr_dashboard/clock_in" },
    { label: "Quick Chat", path: "/hr_dashboard/message" },
  ],
  Payroll: [
    { label: "Dashboard", path: "/Payroll" },
    { label: "Generate Payroll", path: "/Payroll/generate_payroll" },
    { label: "Salary Structure", path: "/Payroll/salary_structure" },
    { label: "View Salary Info", path: "/Payroll/view_employee_salary_info" },
    { label: "Edit Salary Info", path: "/Payroll/edit_employee_salary_info" },
    { label: "Payroll Reports", path: "/Payroll/payroll_reports" },
    { label: "Tax Reports", path: "/Payroll/tax_reports" },
    { label: "View Generated Payslips", path: "/Payroll/view_generated_payslips" },
    { label: "Re-generate Payslips", path: "/Payroll/re_generate_payslips" },
    { label: "Department-wise Payroll", path: "/Payroll/department_wise_paryoll" },
    { label: "My Profile", path: "/Payroll/profile" },
    { label: "Clock In/Out", path: "/Payroll/clock_in" },
    { label: "View Notifications", path: "/Payroll/view_notification" },
    { label: "Send Notifications", path: "/Payroll/send_notification" },
    { label: "Chat", path: "/Payroll/message" },
    { label: "Help Center", path: "/Payroll/HelpCenter" },
    { label: "Settings", path: "/Payroll/setting" },
  ],
  Employee: [
    { label: "Dashboard", path: "/Employee" },
    { label: "Submit Leave Request", path: "/Employee/Request" },
    { label: "My Payslips", path: "/Employee/my-payslips" },
    { label: "My Payroll", path: "/Employee/MyPayroll" },
    { label: "My Attendance", path: "/Employee/myattendance" },
    { label: "My Profile", path: "/Employee/profile" },
    { label: "My Department", path: "/Employee/my-department" },
    { label: "Efficiency Result", path: "/Employee/Efficiency_Result" },
    { label: "Policy", path: "/Employee/policies" },
    { label: "Clock In/Out", path: "/Employee/clock_in" },
    { label: "View Notifications", path: "/Employee/view_notification" },
    { label: "Chat", path: "/Employee/message" },
    { label: "News Feed", path: "/Employee/news" },
    { label: "Help Center", path: "/Employee/HelpCenter" },
    { label: "Settings", path: "/Employee/setting" },
  ],
  "Line Manager": [
    { label: "Dashboard", path: "/department_manager" },
    { label: "Approve/Reject Requests", path: "/department_manager/Approve_Reject" },
    { label: "Employee Attendance", path: "/department_manager/Employee_Attendance" },
    { label: "Efficiency Report", path: "/department_manager/Efficiency_Report" },
    { label: "Overtime Initiation", path: "/department_manager/OverTimeInitiation" },
    { label: "Employee Directory", path: "/department_manager/Employee_Directory" },
    { label: "My Attendance", path: "/department_manager/myattendance" },
    { label: "My Overtime", path: "/department_manager/myovertime" },
    { label: "My Profile", path: "/department_manager/profile" },
    { label: "View Notifications", path: "/department_manager/view_notification" },
    { label: "Send Notifications", path: "/department_manager/send_notification" },
    { label: "Policy", path: "/department_manager/policies" },
    { label: "Clock In/Out", path: "/department_manager/clock_in" },
    { label: "Chat", path: "/department_manager/message" },
    { label: "Help Center", path: "/department_manager/HelpCenter" },
    { label: "Settings", path: "/department_manager/setting" },
  ],
};
